version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/open-ephys-python-tools"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/OEPlugins/paradigm-bridge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/OEPlugins/custom_python_ic_connector"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/OEPlugins/lsl_investigation"
    schedule:
      interval: "weekly"
